/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppConfiguracionRouteImport } from './routes/_app/configuracion'
import { Route as AppCuentasRouteImport } from './routes/_app/cuentas'
import { Route as AppEntregasRouteImport } from './routes/_app/entregas'
import { Route as AppTrabajosRouteImport } from './routes/_app/trabajos'
import { Route as AppConfiguracionIndexRouteImport } from './routes/_app/configuracion/index'
import { Route as AppConfiguracionClinicasRouteImport } from './routes/_app/configuracion/clinicas'
import { Route as AppConfiguracionFasesRouteImport } from './routes/_app/configuracion/fases'
import { Route as AppConfiguracionLaboratorioRouteImport } from './routes/_app/configuracion/laboratorio'
import { Route as AppConfiguracionProductosRouteImport } from './routes/_app/configuracion/productos'
import { Route as AppConfiguracionUsuariosRouteImport } from './routes/_app/configuracion/usuarios'
import { Route as AppTrabajosIndexRouteImport } from './routes/_app/trabajos/index'
import { Route as AppTrabajosCaseIdRouteImport } from './routes/_app/trabajos/$caseId'
import { Route as AppTrabajosNuevoRouteImport } from './routes/_app/trabajos/nuevo'
import { Route as AppConfiguracionClinicasClinicIdRouteImport } from './routes/_app/configuracion/clinicas.$clinicId'
import { Route as AppTrabajosCaseIdEditarRouteImport } from './routes/_app/trabajos/$caseId_.editar'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionRoute = AppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AppRoute,
} as any)
const AppCuentasRoute = AppCuentasRouteImport.update({
  id: '/cuentas',
  path: '/cuentas',
  getParentRoute: () => AppRoute,
} as any)
const AppEntregasRoute = AppEntregasRouteImport.update({
  id: '/entregas',
  path: '/entregas',
  getParentRoute: () => AppRoute,
} as any)
const AppTrabajosRoute = AppTrabajosRouteImport.update({
  id: '/trabajos',
  path: '/trabajos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracionIndexRoute = AppConfiguracionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppConfiguracionRoute,
} as any)
const AppConfiguracionClinicasRoute =
  AppConfiguracionClinicasRouteImport.update({
    id: '/clinicas',
    path: '/clinicas',
    getParentRoute: () => AppConfiguracionRoute,
  } as any)
const AppConfiguracionFasesRoute = AppConfiguracionFasesRouteImport.update({
  id: '/fases',
  path: '/fases',
  getParentRoute: () => AppConfiguracionRoute,
} as any)
const AppConfiguracionLaboratorioRoute =
  AppConfiguracionLaboratorioRouteImport.update({
    id: '/laboratorio',
    path: '/laboratorio',
    getParentRoute: () => AppConfiguracionRoute,
  } as any)
const AppConfiguracionProductosRoute =
  AppConfiguracionProductosRouteImport.update({
    id: '/productos',
    path: '/productos',
    getParentRoute: () => AppConfiguracionRoute,
  } as any)
const AppConfiguracionUsuariosRoute =
  AppConfiguracionUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AppConfiguracionRoute,
  } as any)
const AppTrabajosIndexRoute = AppTrabajosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppTrabajosRoute,
} as any)
const AppTrabajosCaseIdRoute = AppTrabajosCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AppTrabajosRoute,
} as any)
const AppTrabajosNuevoRoute = AppTrabajosNuevoRouteImport.update({
  id: '/nuevo',
  path: '/nuevo',
  getParentRoute: () => AppTrabajosRoute,
} as any)
const AppConfiguracionClinicasClinicIdRoute =
  AppConfiguracionClinicasClinicIdRouteImport.update({
    id: '/$clinicId',
    path: '/$clinicId',
    getParentRoute: () => AppConfiguracionClinicasRoute,
  } as any)
const AppTrabajosCaseIdEditarRoute = AppTrabajosCaseIdEditarRouteImport.update({
  id: '/$caseId_/editar',
  path: '/$caseId/editar',
  getParentRoute: () => AppTrabajosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/configuracion': typeof AppConfiguracionRouteWithChildren
  '/cuentas': typeof AppCuentasRoute
  '/entregas': typeof AppEntregasRoute
  '/trabajos': typeof AppTrabajosRouteWithChildren
  '/configuracion/clinicas': typeof AppConfiguracionClinicasRouteWithChildren
  '/configuracion/fases': typeof AppConfiguracionFasesRoute
  '/configuracion/laboratorio': typeof AppConfiguracionLaboratorioRoute
  '/configuracion/productos': typeof AppConfiguracionProductosRoute
  '/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/trabajos/$caseId': typeof AppTrabajosCaseIdRoute
  '/trabajos/nuevo': typeof AppTrabajosNuevoRoute
  '/configuracion/': typeof AppConfiguracionIndexRoute
  '/trabajos/': typeof AppTrabajosIndexRoute
  '/configuracion/clinicas/$clinicId': typeof AppConfiguracionClinicasClinicIdRoute
  '/trabajos/$caseId/editar': typeof AppTrabajosCaseIdEditarRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/cuentas': typeof AppCuentasRoute
  '/entregas': typeof AppEntregasRoute
  '/': typeof AppIndexRoute
  '/configuracion/clinicas': typeof AppConfiguracionClinicasRouteWithChildren
  '/configuracion/fases': typeof AppConfiguracionFasesRoute
  '/configuracion/laboratorio': typeof AppConfiguracionLaboratorioRoute
  '/configuracion/productos': typeof AppConfiguracionProductosRoute
  '/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/trabajos/$caseId': typeof AppTrabajosCaseIdRoute
  '/trabajos/nuevo': typeof AppTrabajosNuevoRoute
  '/configuracion': typeof AppConfiguracionIndexRoute
  '/trabajos': typeof AppTrabajosIndexRoute
  '/configuracion/clinicas/$clinicId': typeof AppConfiguracionClinicasClinicIdRoute
  '/trabajos/$caseId/editar': typeof AppTrabajosCaseIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/configuracion': typeof AppConfiguracionRouteWithChildren
  '/_app/cuentas': typeof AppCuentasRoute
  '/_app/entregas': typeof AppEntregasRoute
  '/_app/trabajos': typeof AppTrabajosRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/configuracion/clinicas': typeof AppConfiguracionClinicasRouteWithChildren
  '/_app/configuracion/fases': typeof AppConfiguracionFasesRoute
  '/_app/configuracion/laboratorio': typeof AppConfiguracionLaboratorioRoute
  '/_app/configuracion/productos': typeof AppConfiguracionProductosRoute
  '/_app/configuracion/usuarios': typeof AppConfiguracionUsuariosRoute
  '/_app/trabajos/$caseId': typeof AppTrabajosCaseIdRoute
  '/_app/trabajos/nuevo': typeof AppTrabajosNuevoRoute
  '/_app/configuracion/': typeof AppConfiguracionIndexRoute
  '/_app/trabajos/': typeof AppTrabajosIndexRoute
  '/_app/configuracion/clinicas/$clinicId': typeof AppConfiguracionClinicasClinicIdRoute
  '/_app/trabajos/$caseId_/editar': typeof AppTrabajosCaseIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/configuracion'
    | '/cuentas'
    | '/entregas'
    | '/trabajos'
    | '/configuracion/clinicas'
    | '/configuracion/fases'
    | '/configuracion/laboratorio'
    | '/configuracion/productos'
    | '/configuracion/usuarios'
    | '/trabajos/$caseId'
    | '/trabajos/nuevo'
    | '/configuracion/'
    | '/trabajos/'
    | '/configuracion/clinicas/$clinicId'
    | '/trabajos/$caseId/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/cuentas'
    | '/entregas'
    | '/'
    | '/configuracion/clinicas'
    | '/configuracion/fases'
    | '/configuracion/laboratorio'
    | '/configuracion/productos'
    | '/configuracion/usuarios'
    | '/trabajos/$caseId'
    | '/trabajos/nuevo'
    | '/configuracion'
    | '/trabajos'
    | '/configuracion/clinicas/$clinicId'
    | '/trabajos/$caseId/editar'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/configuracion'
    | '/_app/cuentas'
    | '/_app/entregas'
    | '/_app/trabajos'
    | '/_app/'
    | '/_app/configuracion/clinicas'
    | '/_app/configuracion/fases'
    | '/_app/configuracion/laboratorio'
    | '/_app/configuracion/productos'
    | '/_app/configuracion/usuarios'
    | '/_app/trabajos/$caseId'
    | '/_app/trabajos/nuevo'
    | '/_app/configuracion/'
    | '/_app/trabajos/'
    | '/_app/configuracion/clinicas/$clinicId'
    | '/_app/trabajos/$caseId_/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion': {
      id: '/_app/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof AppConfiguracionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cuentas': {
      id: '/_app/cuentas'
      path: '/cuentas'
      fullPath: '/cuentas'
      preLoaderRoute: typeof AppCuentasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entregas': {
      id: '/_app/entregas'
      path: '/entregas'
      fullPath: '/entregas'
      preLoaderRoute: typeof AppEntregasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trabajos': {
      id: '/_app/trabajos'
      path: '/trabajos'
      fullPath: '/trabajos'
      preLoaderRoute: typeof AppTrabajosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/configuracion/': {
      id: '/_app/configuracion/'
      path: '/'
      fullPath: '/configuracion/'
      preLoaderRoute: typeof AppConfiguracionIndexRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/configuracion/clinicas': {
      id: '/_app/configuracion/clinicas'
      path: '/clinicas'
      fullPath: '/configuracion/clinicas'
      preLoaderRoute: typeof AppConfiguracionClinicasRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/configuracion/fases': {
      id: '/_app/configuracion/fases'
      path: '/fases'
      fullPath: '/configuracion/fases'
      preLoaderRoute: typeof AppConfiguracionFasesRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/configuracion/laboratorio': {
      id: '/_app/configuracion/laboratorio'
      path: '/laboratorio'
      fullPath: '/configuracion/laboratorio'
      preLoaderRoute: typeof AppConfiguracionLaboratorioRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/configuracion/productos': {
      id: '/_app/configuracion/productos'
      path: '/productos'
      fullPath: '/configuracion/productos'
      preLoaderRoute: typeof AppConfiguracionProductosRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/configuracion/usuarios': {
      id: '/_app/configuracion/usuarios'
      path: '/usuarios'
      fullPath: '/configuracion/usuarios'
      preLoaderRoute: typeof AppConfiguracionUsuariosRouteImport
      parentRoute: typeof AppConfiguracionRoute
    }
    '/_app/trabajos/': {
      id: '/_app/trabajos/'
      path: '/'
      fullPath: '/trabajos/'
      preLoaderRoute: typeof AppTrabajosIndexRouteImport
      parentRoute: typeof AppTrabajosRoute
    }
    '/_app/trabajos/$caseId': {
      id: '/_app/trabajos/$caseId'
      path: '/$caseId'
      fullPath: '/trabajos/$caseId'
      preLoaderRoute: typeof AppTrabajosCaseIdRouteImport
      parentRoute: typeof AppTrabajosRoute
    }
    '/_app/trabajos/nuevo': {
      id: '/_app/trabajos/nuevo'
      path: '/nuevo'
      fullPath: '/trabajos/nuevo'
      preLoaderRoute: typeof AppTrabajosNuevoRouteImport
      parentRoute: typeof AppTrabajosRoute
    }
    '/_app/configuracion/clinicas/$clinicId': {
      id: '/_app/configuracion/clinicas/$clinicId'
      path: '/$clinicId'
      fullPath: '/configuracion/clinicas/$clinicId'
      preLoaderRoute: typeof AppConfiguracionClinicasClinicIdRouteImport
      parentRoute: typeof AppConfiguracionClinicasRoute
    }
    '/_app/trabajos/$caseId_/editar': {
      id: '/_app/trabajos/$caseId_/editar'
      path: '/$caseId/editar'
      fullPath: '/trabajos/$caseId/editar'
      preLoaderRoute: typeof AppTrabajosCaseIdEditarRouteImport
      parentRoute: typeof AppTrabajosRoute
    }
  }
}

interface AppConfiguracionClinicasRouteChildren {
  AppConfiguracionClinicasClinicIdRoute: typeof AppConfiguracionClinicasClinicIdRoute
}

const AppConfiguracionClinicasRouteChildren: AppConfiguracionClinicasRouteChildren =
  {
    AppConfiguracionClinicasClinicIdRoute:
      AppConfiguracionClinicasClinicIdRoute,
  }

const AppConfiguracionClinicasRouteWithChildren =
  AppConfiguracionClinicasRoute._addFileChildren(
    AppConfiguracionClinicasRouteChildren,
  )

interface AppConfiguracionRouteChildren {
  AppConfiguracionClinicasRoute: typeof AppConfiguracionClinicasRouteWithChildren
  AppConfiguracionFasesRoute: typeof AppConfiguracionFasesRoute
  AppConfiguracionLaboratorioRoute: typeof AppConfiguracionLaboratorioRoute
  AppConfiguracionProductosRoute: typeof AppConfiguracionProductosRoute
  AppConfiguracionUsuariosRoute: typeof AppConfiguracionUsuariosRoute
  AppConfiguracionIndexRoute: typeof AppConfiguracionIndexRoute
}

const AppConfiguracionRouteChildren: AppConfiguracionRouteChildren = {
  AppConfiguracionClinicasRoute: AppConfiguracionClinicasRouteWithChildren,
  AppConfiguracionFasesRoute: AppConfiguracionFasesRoute,
  AppConfiguracionLaboratorioRoute: AppConfiguracionLaboratorioRoute,
  AppConfiguracionProductosRoute: AppConfiguracionProductosRoute,
  AppConfiguracionUsuariosRoute: AppConfiguracionUsuariosRoute,
  AppConfiguracionIndexRoute: AppConfiguracionIndexRoute,
}

const AppConfiguracionRouteWithChildren =
  AppConfiguracionRoute._addFileChildren(AppConfiguracionRouteChildren)

interface AppTrabajosRouteChildren {
  AppTrabajosCaseIdRoute: typeof AppTrabajosCaseIdRoute
  AppTrabajosNuevoRoute: typeof AppTrabajosNuevoRoute
  AppTrabajosIndexRoute: typeof AppTrabajosIndexRoute
  AppTrabajosCaseIdEditarRoute: typeof AppTrabajosCaseIdEditarRoute
}

const AppTrabajosRouteChildren: AppTrabajosRouteChildren = {
  AppTrabajosCaseIdRoute: AppTrabajosCaseIdRoute,
  AppTrabajosNuevoRoute: AppTrabajosNuevoRoute,
  AppTrabajosIndexRoute: AppTrabajosIndexRoute,
  AppTrabajosCaseIdEditarRoute: AppTrabajosCaseIdEditarRoute,
}

const AppTrabajosRouteWithChildren = AppTrabajosRoute._addFileChildren(
  AppTrabajosRouteChildren,
)

interface AppRouteChildren {
  AppConfiguracionRoute: typeof AppConfiguracionRouteWithChildren
  AppCuentasRoute: typeof AppCuentasRoute
  AppEntregasRoute: typeof AppEntregasRoute
  AppTrabajosRoute: typeof AppTrabajosRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppConfiguracionRoute: AppConfiguracionRouteWithChildren,
  AppCuentasRoute: AppCuentasRoute,
  AppEntregasRoute: AppEntregasRoute,
  AppTrabajosRoute: AppTrabajosRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
